# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: journalex
      POSTGRES_PASSWORD: journalex
      POSTGRES_DB: journalex_dev
      PGDATA: /var/lib/postgresql/data/journalex/
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 6543:5432
    networks:
      - journalex_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U journalex -d journalex_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - 4008:4008
    depends_on:
      db:
        condition: service_healthy
    # command: [
    #   "sh",
    #   "-c",
    #   "mix deps.get && mix ecto.migrate && mix phx.server"
    # ]
    command: [
      "sh",
      "-c",
      "mix deps.get && mix ecto.reset && mix phx.server"
    ]
    environment:
      MIX_ENV: dev
      NOTION_API_TOKEN: "${NOTION_API_TOKEN}"
      NOTION_ACTIVITY_STATEMENT_DATA_SOURCE_ID: "${NOTION_ACTIVITY_STATEMENT_DATA_SOURCE_ID}"
      NOTION_TRADES_DATA_SOURCE_ID: "${NOTION_TRADES_DATA_SOURCE_ID}"
      NOTION_TRADES_V1_DATA_SOURCE_ID: "${NOTION_TRADES_V1_DATA_SOURCE_ID}"
      NOTION_TRADES_V2_DATA_SOURCE_ID: "${NOTION_TRADES_V2_DATA_SOURCE_ID}"
      NOTION_TICKER_DETAILS_DATA_SOURCE_ID: "${NOTION_TICKER_DETAILS_DATA_SOURCE_ID}"
      NOTION_MARKET_DAILY_DATA_SOURCE_ID: "${NOTION_MARKET_DAILY_DATA_SOURCE_ID}"

      NOTION_DATETIME_PROPERTY: "${NOTION_DATETIME_PROPERTY}"
      NOTION_VERSION: "${NOTION_VERSION}"
    networks:
      - journalex_app
networks:
  journalex_app: